### PR TITLE
Made separate HTML template file for navbar and added it to all pages

### PR DESCRIPTION
**Pull request by docjon09**
This PR is related to issue #7
Previously, only the main page had navbar. I have copied the navbar code into a separate HTML template file. Then, I added it to all pages except login and logout using django include tags. This will reduce code duplication and improve consistency.

### CODE REVIEW

**Comment by docjon09** [comment]
@Sahilopl , @ADITYAVOFFICIAL , please review these changes.

**Review by ADITYAVOFFICIAL — APPROVED** [review]
Reviewed changes; required updates were made, and the build functions correctly. Good work, aligns with project standards.

**Comment by Sahilopl** [comment]
Awesome work thanks for your potential support we  appreciate your work support for our repo and will merge it into our project after our member Aditya Verma deep review over it. Happy hacking!!

**Comment by ADITYAVOFFICIAL** [comment]
I'll be closing the issue as it's resolved. Repo merging in 5 minutes. Thanks for Hacktoberfest contributions! Feel free to create more issues. Good luck in your future contributions!

**Pull request merged**
